filt:
  main:
    rt_sigma: 0.8
    sm_thr: 30
    dn_ttsmooth: true
    sm_pref_mode: 2
    dn_pref: false
    dn_expr: x 1500 +
    cs_val: 0.1
    #
    db_thr: 1.0
    db_mode: 3
    db_rt_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 3
        db_thr: 5
        db_mode: 3
        #
    ag_str: 0.3
    ag_scaling: 10
    ag_saveblack: 2
