filt:
  main:
    rt_sigma: 1
    sm_thr: 40
    cs_val: 0.7
    #
    db_thr: 2.1
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 1
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 10
    ag_saveblack: 1
  ed:
    db_saveblack: 2
    ag_saveblack: 2
  noise:
    cs_val: 0.2
  next:
    cs_val: 0.5
    db_thr: 2.0
    ag_str: 0.2

aa:
  main:
    desc_h: 848
    # desc_h: [847, 848, 849]
    desc_str: 0.32
    kernel: bicubic
    # bic_b: 1/3
    # bic_c: 1/3

dehalo:
  main:
    rx: 2
    darkstr: 0
    brightstr: 0.6
