[tool.poetry]
name = "encode-scripts"
version = "0.0.0"
description = "Vapoursynth scripts"
authors = ["DeadNews <aurczpbgr@mozmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
vapoursynth = ">=60"
dnfunc = "^0.0.4"
pyyaml = "^6.0"

[tool.poetry.group.lint.dependencies]
black = "^23.7.0"
ruff = "^0.0.286"

[tool.poetry.group.runtime.dependencies]
vspreview = "^0.7.1"
numpy = "^1.25.2"

[tool.black]
line-length = 99

[tool.ruff]
line-length = 99
select = ["ALL"]
ignore = [
  "COM812",  # Trailing comma missing
  "D203",    # 1 blank line required before class docstring
  "D212",    # Multi-line docstring summary should start at the first line
  "E501",    # Line too long
  "EXE001",  # Shebang is present but file is not executable
  "FBT001",  # Boolean positional arg in function definition
  "FBT002",  # Boolean default value in function definition
  "PERF203", # `try`-`except` within a loop incurs performance overhead
  #
  "BLE001", # Do not catch blind exception: `Exception`
  "D100",   # Missing docstring in public module
  "D103",   # Missing docstring in public function
  "E402",   # Module level import not at top of file
  "ERA001", # Found commented-out code
  "INP001", # File {filename} is part of an implicit namespace package. Add an __init__.py.
  "T201",   # `print` found
]

[tool.ruff.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = false

[tool.ruff.flake8-annotations]
ignore-fully-untyped = true
