[tool.black]
line-length = 99

[tool.isort]
line_length = 99
profile = "black"

[tool.flake8]
max-line-length = 99
max-complexity = 18
show-source = true
# statistics = true
ignore = [
  "C408",   # Unnecessary dict call.
  "E203",   # Whitespace before ':'.
  "E501",   # Line too long.
  "PIE786", # Use precise exception handlers.
  "PIE803", # Use lazy % formatting in logging functions.
  "W503",   # Line break occurred before a binary operator.
  # Temp:
  "E402", # Module level import not at top of file.
]

[tool.mypy]
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
show_column_numbers = true
show_error_codes = true
warn_unused_ignores = true
