filt:
  main:
    rt_sigma: 1
    sm_thr: 47
    dn_ttsmooth: true
    sm_pref_mode: 2
    dn_pref: true
    cs_val: 0.62
    #
    db_thr: 2.1
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 3
        db_thr: 3.8
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 52
    ag_saveblack: 2
  dark:
    sm_thr: 34
    cs_val: 0.36
    db_thr: 2.0
    ag_scaling: 12
    ag_saveblack: 1

aa:
  main:
    desc_h: 900
    desc_str: 0.99
    kernel: bicubic
    bic_b: 0.2
    bic_c: 0.5
    #
    resc_mthr: 35
    resc_bc: true

dehalo:
  main:
    rx: 1.6
    darkstr: 0
    brightstr: 0.85
