filt:
  main:
    rt_sigma: 1
    sm_thr: 28
    dn_ttsmooth: true
    sm_pref_mode: 1
    dn_pref: false
    cs_val: 0.4
    #
    db_thr: 1.0
    db_mode: 3
    db_det: 60
    db_grain: 38
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 4
        db_thr: 5
        db_mode: 3
        #
    ag_str: 0
    ag_scaling: 40
    ag_saveblack: 2
  pv:
    sm_thr: 64
    dn_ttsmooth: true
    sm_pref_mode: 2
    dn_pref: true
    cs_val: 0.6
    #
    db_thr: 1.1
