filt:
  main:
    rt_sigma: 1
    sm_thr: 54
    cs_val: 0.7
    #
    db_thr: 2.1
    db_mode: 3
    db_rt_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0
    ag_scaling: 10
    ag_saveblack: 2

aa:
  main:
    desc_h: 878
    desc_str: 0.3
    kernel: bilinear
    gamma: 1000

dehalo:
  main:
    rx: 1.6
    darkstr: 0
    brightstr: 1.0
