filt:
  main:
    # rt_sigma: 1
    rt_sigma: 2
    sm_thr: 40
    sm_pref_mode: 1
    dn_pref: true
    dn_adaptive:
      z2:
        scaling: 3
        sm_thr: 200
        sm_pref_mode: 2
    cs_mode: 1
    cs_val: 0.05
    #
    db_thr: 1
    db_mode: 3
    db_rt_mode: 3
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 3
        db_thr: 8.0
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 1
    ag_saveblack: 1
  op:
    sm_thr: 50
    dn_pref: true
    cs_val: 0.4
    ag_str: 0.1
    ag_scaling: 12
  ed:
    sm_thr: 37
    dn_pref: true
    cs_val: 0.4
    ag_str: 0.1
    ag_scaling: 12
    ag_saveblack: 2

dehalo:
  main:
    #  rx: 1.8  # check --no
    rx: 1.5
    darkstr: 0.0
    brightstr: 2.1
    mode: kirsch
    max_c: 3
    min_c: 1

crop:
  main:
    left: 200
    right: 200

edgefix:
  main:
    # top: 1
    # bottom: 1
    left: 2
    right: 2
