filt:
  main:
    rt_sigma: 0.9
    sm_thr: 18
    dn_ttsmooth: true
    sm_pref_mode: 1
    dn_pref: false
    # dn_expr: x 700 +
    cs_val: 0.7
    #
    db_thr: 1
    db_mode: 3
    db_gf_mode: 1
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 8
    ag_saveblack: 1
  op:
    cs_val: 0.4
    ag_str: 0.2
  menu:
    cs_val: 0.4
    db_thr: 1.1
    ag_saveblack: 2

aa:
  main:
    desc_h: 806 # eedi
    gamma: 110
    nrad: 3

dehalo:
  main:
    rx: 1.4
    darkstr: 0
    brightstr: 1

crop:
  main:
    top: 136
    bottom: 138
