filt:
  main:
    rt_sigma: 1
    sm_thr: 45
    dn_ttsmooth: true
    sm_pref_mode: 1
    dn_pref: false
    cs_val: 0.55
    #
    db_thr: 1.0
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0
    ag_scaling: 50
    ag_saveblack: 2

aa:
  main:
    desc_h: 864
    desc_str: 0.99
    kernel: bicubic
    gamma: 650
  hard:
    gamma: 1
  resc1:
    resc_mthr: 18
  resc2:
    resc_mthr: 20

dehalo:
  main:
    rx: 1.6
    darkstr: 0
    brightstr: 0.8

edgefix:
  main:
    top: 1
    bottom: 1
    left: 1
    right: 1
