filt:
  main:
    rt_sigma: 1
    sm_thr: 70
    # sm_thr: 60
    # dn_pref: false
    dn_pref: true
    cs_val: 0.5
    #
    db_thr: 2.2
    db_mode: 1
    db_rt_mode: 2
    db_grain: 58
    db_saveblack: 1
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 2.8
        db_mode: 1
        #
    ag_str: 0.2
    ag_scaling: 6
    ag_saveblack: 1

aa:
  main:
    # desc_h: 540
    desc_h: 720
    # desc_h: 1053
    desc_str: 0.30
    # desc_str: 0.50
    # kernel: bilinear
    kernel: lanczos
    taps: 4
    gamma: 1000

dehalo:
  main:
    rx: 2
    darkstr: 0
    brightstr: 1

crop:
  top: 7
  bottom: 4
  left: 10
  right: 8

edgefix:
  top: 0
  bottom: 0
  left: 2
  right: 2
