filt:
  main:
    rt_sigma: 1
    sm_thr: 70
    dn_pref: false
    cs_val: 0.5
    #
    db_thr: 2.2
    db_mode: 1
    db_rt_mode: 2
    db_grain: 54
    db_saveblack: 1
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 2.8
        db_mode: 1
        #
    ag_str: 0.12
    ag_scaling: 12
    ag_saveblack: 1
  next:
    db_saveblack: 2
    db_saveblack_tolerance: 4
    ag_saveblack: 2
    ag_saveblack_tolerance: 4
  op:
    sm_thr: 80
  ed:
    sm_thr: 200
    dn_pref: true
    ag_str: 0.2

aa:
  main:
    desc_h: 540
    desc_str: 0.80
    kernel: bilinear
    alpha: 0.2
    beta: 0.25
    gamma: 1.0

dehalo:
  main:
    rx: 2.5
    darkstr: 0.6
    brightstr: 1.5
    mode: kirsch
    max_c: 6
    min_c: 1
  2nd:
    darkstr: 0
  3nd:
    rx: 2.0
    darkstr: 0

crop:
  top: 0
  bottom: 0
  left: 240
  right: 240

edgefix:
  top: 0
  bottom: 0
  left: 5
  right: 0
