filt:
  main:
    rt_sigma: 1
    # sm_thr: 24
    sm_thr: 30
    dn_ttsmooth: true
    sm_pref_mode: 1
    # sm_pref_mode: 2
    dn_pref: false
    cs_val: 0.5
    #
    db_thr: 1.0
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 1
        db_thr: 5
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 18
    ag_saveblack: 2

aa:
  main:
    desc_h: 720
    desc_str: 0.99
    kernel: bicubic
    bic_b: 0.2
    bic_c: 0.4
    gamma: 1000
    #
    resc_mthr: 65
    resc_bc: true
  op:
    resc_mthr: 35

edgefix:
  main:
    top: 1
    bottom: 1
    left: 1
    right: 1
