filt:
  main:
    rt_sigma: 1
    sm_thr: 35
    dn_ttsmooth: true
    sm_pref_mode: 2
    dn_pref: true
    cs_val: 0.60
    #
    db_thr: 1.1
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 1.6
        db_thr: 3.8
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 150
    ag_saveblack: 2
  dark:
    sm_thr: 20
    cs_val: 0.33
    ag_scaling: 20

aa:
  main:
    desc_h: 810
    desc_str: 0.99
    kernel: bicubic
    bic_b: 0
    bic_c: 0.75
    #
    resc_mthr: 38
    resc_bc: true

dehalo:
  main:
    rx: 1.6
    darkstr: 0
    brightstr: 0.8
