filt:
  main:
    rt_sigma: 0.9
    sm_thr: 48
    dn_ttsmooth: true
    cs_val: 0.74
    #
    db_thr: 1
    db_mode: 3
    db_gf_mode: 1
    db_rt_mode: 2
    db_det: 60
    db_grain: 46
    db_range: 10
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0
    ag_scaling: 12
    ag_saveblack: 2
  harder:
    sm_thr: 96
    sm_pref_mode: 2
  harder_2:
    sm_thr: 96
    sm_pref_mode: 2
    db_rt_mode: 3
    db_gf_mode: 3
  harder_3:
    sm_pref_mode: 2
    cs_val: 0.35
    db_rt_mode: 3
    db_gf_mode: 3
    ag_str: 0.3
    ag_scaling: 2
  harder_e9:
    sm_thr: 68
    sm_pref_mode: 2
    dn_pref: true
    cs_val: 0.35
    db_rt_mode: 3
    db_gf_mode: 3
    ag_str: 0.3
    ag_scaling: 2
