filt:
  main:
    rt_sigma: 1
    # sm_thr: 34
    sm_thr: 58
    dn_ttsmooth: true
    sm_pref_mode: 1
    dn_pref: false
    cs_val: 0.6
    #
    db_thr: 1.0
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 1
    db_adaptive:
      z2:
        scaling: 4.5
        db_thr: 5
        db_mode: 3
        #
    ag_str: 0.20
    ag_scaling: 18
    ag_saveblack: 2

# aa:
#     main:
#         desc_h: 810
#         desc_str: 0.32
#         kernel: bicubic
#         bic_b: 0.2
#         bic_c: 0.5
#         gamma: 1000
#         #
#         resc_mthr: 25
#         resc_bc: true

dehalo:
  main:
    rx: 1.3
    darkstr: 0
    brightstr: 0.7
