filt:
  main:
    rt_sigma: 1
    sm_thr: 56
    dn_ttsmooth: true
    sm_pref_mode: 2
    dn_pref: false
    cs_val: 0.5
    #
    db_thr: 1
    db_mode: 3
    db_det: 60
    db_grain: 58
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 5
        db_thr: 5
        db_mode: 3
        #
    ag_str: 0.16
    ag_scaling: 24
    ag_saveblack: 2
