filt:
  main:
    rt_sigma: 1
    sm_thr: 40
    cs_val: 0.7
    #
    db_thr: 2.0
    db_mode: 3
    db_gf_mode: 1
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 3.8
        db_mode: 3
        #
    ag_str: 0
    ag_scaling: 1
    ag_saveblack: 2
  ed1:
    rt_sigma: 2
    sm_thr: 50
    dn_pref: true
    cs_val: 0.5
    db_thr: 2.1
    ag_str: 0.5
  ed2:
    sm_thr: 50
  timelapse:
    sm_thr: 50
    dn_pref: true
    cs_val: 0.35
    db_grain: 18

aa:
  main:
    desc_h: 830
    desc_str: 0.26
    kernel: bicubic
    gamma: 1000
    bic_b: 0.5
    bic_c: 0.5
    #
    # desc_str: 0.90
    # kernel: lanczos
    # taps: 4

dehalo:
  main:
    rx: 2
    darkstr: 0
    brightstr: 0.6
