filt:
  main:
    rt_sigma: 1
    sm_thr: 40
    dn_ttsmooth: true
    sm_pref_mode: 2
    dn_pref: true
    # cs_val: 0.5
    cs_val: 0.75
    #
    db_thr: 2.1
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0.18
    ag_scaling: 50
    ag_saveblack: 2
  oped:
    ag_str: 0
  ed_lite:
    sm_thr: 30
  menu:
    db_grain: 18
    ag_str: 0
  e8_avant:
    sm_thr: 50

aa:
  main:
    desc_h: 838
    desc_str: 0.32
    kernel: bicubic
    bic_b: 0.5
    bic_c: 0
    gamma: 950

dehalo:
  main:
    rx: 1.6
    darkstr: 0
    brightstr: 0.7
