filt:
  main:
    rt_sigma: 1
    sm_thr: 25
    dn_ttsmooth: true
    sm_pref_mode: 1
    dn_pref: false
    cs_val: 0.65
    #
    db_thr: 1.0
    db_mode: 3
    db_det: 60
    db_grain: 48
    db_saveblack: 2
    db_adaptive:
      z2:
        scaling: 0.1
        db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0.12
    ag_scaling: 50
    ag_saveblack: 2
  menu:
    cs_val: 0.01

aa:
  main:
    desc_h: 828
    desc_str: 0.99
    kernel: bicubic
    bic_b: 0.2
    bic_c: 0.4
    gamma: 800
    #
    resc_mthr: 38
    resc_bc: true
  nc:
    resc_mthr: 18

dehalo:
  main:
    rx: 1.6
    darkstr: 0
    brightstr: 1
