filt:
  main:
    rt_sigma: 1
    sm_thr: 90
    dn_pref: true
    dn_pref_mul: 1
    cs_mode: 2
    cs_val: 0.5
    #
    db_thr: 1.1
    db_mode: 3
    db_gf_mode: 3
    db_rt_mode: 4
    db_grain: 40
    db_saveblack: 1
    db_adaptive:
      z2:
        scaling: 14
        db_thr: 9
        db_mode: 3
        #
    ag_str: 0.02
    ag_scaling: 12
  soft1:
    sm_thr: 70
    dn_pref_mul: 0.3
    db_adaptive:
      z2:
        scaling: 11
        db_thr: 9
        db_mode: 3
  soft2:
    dn_pref_mul: 0.3
    cs_val: 0.7
  limb:
    db_thr: 2.5
    db_mode: 2
    db_det: 68
    ag_str: 0.12
    ag_scaling: 16
    db_adaptive:
      z2:
        scaling: 12
        db_thr: 5
        db_mode: 2
  noise:
    ag_str: 0.2
    ag_scaling: 0
  saveblack:
    db_saveblack: 2
    ag_saveblack: 2

aa:
  main:
    desc_h: 900
    desc_str: 0.26
    kernel: bicubic
    bic_b: 1
    bic_c: 0
  resc:
    bic_b: 0.3333333333333333
    bic_c: 0.3333333333333333

dehalo:
  main:
    rx: 2
    darkstr: 0
    brightstr: 1
