filt:
  main:
    rt_sigma: 1
    sm_thr: 40
    dn_pref: true
    cs_val: 0.35
    #
    db_thr: 2.1
    db_mode: 3
    db_rt_mode: 3
    db_gf_mode: 3
    db_det: 60
    db_grain: 46
    db_saveblack: 1
    db_adaptive:
      z2:
        # scaling: 3
        # db_thr: 4.0
        scaling: 6
        db_thr: 2.6
        # scaling: 0.1
        # db_thr: 4.0
        db_mode: 3
        #
    ag_str: 0
    ag_scaling: 12
    ag_saveblack: 1
  ed:
    db_thr: 2.2
  ed2:
    db_saveblack: 2
  noise:
    cs_val: 0.20

aa:
  main:
    desc_h: 810
    desc_str: 0.36
    kernel: bicubic
    gamma: 1000
  resc:
    bic_b: 1.00
    bic_c: 1.00
